import type { Component } from "../types";

/**
 * A representative subset of the assembly — 45 placements laid out on the
 * 100 x 80 mm outline defined in `mockBoard.ts`.
 *
 * Positions use the board's bottom-left origin in mm, the same convention a
 * real pick-and-place file uses. Footprints are roughly true to their packages
 * so the rendered board reads at the correct scale.
 *
 * The four `calloutIndex` parts are the ones pinned in the viewport, and the
 * refDes values referenced by `mockIssues.ts` (C236, U7, R102, J3) carry
 * matching non-Verified statuses.
 */
export const mockComponents: Component[] = [
  // ---------------------------------------------------------------- ICs
  {
    id: "c-u14",
    refDes: "U14",
    name: "Microcontroller",
    package: "QFP-64",
    kind: "IC",
    side: "Top",
    position: { x: 46.35, y: 32.1 },
    rotation: 90,
    height: 1.6,
    footprint: { width: 10, depth: 10 },
    supplier: "Texas Instruments",
    partNumber: "TMS320F28027PTT",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1 },
    offsetMm: 0.042,
    notes: "Within tolerance. All pins aligned.",
    calloutIndex: 1,
  },
  {
    id: "c-u7",
    refDes: "U7",
    name: "Ethernet PHY",
    package: "QFN-48",
    kind: "IC",
    side: "Top",
    position: { x: 68, y: 46 },
    rotation: 180,
    height: 0.9,
    footprint: { width: 7, depth: 7 },
    supplier: "Microchip",
    partNumber: "KSZ8081RNBIA",
    status: "Critical",
    tolerance: { xy: 0.08, rot: 1 },
    offsetMm: 0.061,
    notes: "Rotation mismatch against BOM: placed 180°, expected 90°.",
    calloutIndex: 4,
  },
  {
    id: "c-u1",
    refDes: "U1",
    name: "Buck Regulator",
    package: "SOIC-8",
    kind: "IC",
    side: "Top",
    position: { x: 24, y: 34 },
    rotation: 0,
    height: 1.75,
    footprint: { width: 5, depth: 4 },
    supplier: "Texas Instruments",
    partNumber: "LM2596S-5.0",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.03,
  },
  {
    id: "c-u2",
    refDes: "U2",
    name: "Gate Driver",
    package: "SOIC-16",
    kind: "IC",
    side: "Top",
    position: { x: 30, y: 50 },
    rotation: 0,
    height: 1.75,
    footprint: { width: 10, depth: 4 },
    supplier: "Infineon",
    partNumber: "IR2110STRPBF",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.055,
  },
  {
    id: "c-u3",
    refDes: "U3",
    name: "Precision Op Amp",
    package: "SOIC-8",
    kind: "IC",
    side: "Top",
    position: { x: 76, y: 26 },
    rotation: 90,
    height: 1.75,
    footprint: { width: 5, depth: 4 },
    supplier: "Analog Devices",
    partNumber: "AD8620ARZ",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.028,
  },
  {
    id: "c-u5",
    refDes: "U5",
    name: "CAN Transceiver",
    package: "SOIC-8",
    kind: "IC",
    side: "Top",
    position: { x: 86, y: 40 },
    rotation: 270,
    height: 1.75,
    footprint: { width: 5, depth: 4 },
    supplier: "NXP",
    partNumber: "TJA1050T/CM",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.037,
  },
  {
    id: "c-u8",
    refDes: "U8",
    name: "Serial Flash",
    package: "SOP-8",
    kind: "IC",
    side: "Top",
    position: { x: 58, y: 20 },
    rotation: 0,
    height: 1.75,
    footprint: { width: 6, depth: 5 },
    supplier: "Winbond",
    partNumber: "W25Q128JVSIQ",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.044,
  },
  {
    id: "c-u9",
    refDes: "U9",
    name: "EEPROM",
    package: "TSSOP-8",
    kind: "IC",
    side: "Top",
    position: { x: 50, y: 12 },
    rotation: 0,
    height: 1.1,
    footprint: { width: 3, depth: 3 },
    supplier: "STMicroelectronics",
    partNumber: "M24C64-RMN6TP",
    status: "Verified",
    tolerance: { xy: 0.08, rot: 1 },
    offsetMm: 0.019,
  },
  {
    id: "c-u11",
    refDes: "U11",
    name: "Level Shifter",
    package: "TSSOP-20",
    kind: "IC",
    side: "Top",
    position: { x: 36, y: 20 },
    rotation: 90,
    height: 1.1,
    footprint: { width: 6.5, depth: 4.4 },
    supplier: "Texas Instruments",
    partNumber: "TXB0108PWR",
    status: "Verified",
    tolerance: { xy: 0.08, rot: 1 },
    offsetMm: 0.033,
  },
  {
    id: "c-u12",
    refDes: "U12",
    name: "RS-485 Driver",
    package: "SOIC-8",
    kind: "IC",
    side: "Top",
    position: { x: 88, y: 48 },
    rotation: 270,
    height: 1.75,
    footprint: { width: 5, depth: 4 },
    supplier: "Maxim Integrated",
    partNumber: "MAX485ESA+",
    status: "Warning",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.092,
    notes: "Positional offset approaching the tolerance limit.",
  },

  // ------------------------------------------------------ Electrolytics
  {
    id: "c-c1",
    refDes: "C1",
    name: "Bulk Capacitor",
    package: "Radial 10mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 14, y: 69 },
    rotation: 0,
    height: 20,
    footprint: { width: 10, depth: 10 },
    supplier: "Nichicon",
    partNumber: "UHE1V101MPD",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.071,
  },
  {
    id: "c-c2",
    refDes: "C2",
    name: "Bulk Capacitor",
    package: "Radial 10mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 26, y: 71 },
    rotation: 0,
    height: 20,
    footprint: { width: 10, depth: 10 },
    supplier: "Nichicon",
    partNumber: "UHE1V101MPD",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.064,
  },
  {
    id: "c-c3",
    refDes: "C3",
    name: "Input Filter Capacitor",
    package: "Radial 8mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 37, y: 73 },
    rotation: 0,
    height: 16,
    footprint: { width: 8, depth: 8 },
    supplier: "Panasonic",
    partNumber: "EEUFR1V471L",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.088,
  },
  {
    id: "c-c112",
    refDes: "C112",
    name: "Output Filter Capacitor",
    package: "Radial 12.5mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 72, y: 70 },
    rotation: 0,
    height: 25,
    footprint: { width: 12.5, depth: 12.5 },
    supplier: "Rubycon",
    partNumber: "16ZLH1000MEFC",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.053,
    notes: "Tallest part on the top side. Clears the enclosure lid by 4.2 mm.",
    calloutIndex: 2,
  },
  {
    id: "c-c4",
    refDes: "C4",
    name: "Decoupling Bank",
    package: "Radial 6.3mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 86, y: 72 },
    rotation: 0,
    height: 11,
    footprint: { width: 6.3, depth: 6.3 },
    supplier: "Panasonic",
    partNumber: "EEUFC1V101",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.047,
  },
  {
    id: "c-c5",
    refDes: "C5",
    name: "Snubber Capacitor",
    package: "Radial 8mm",
    kind: "Electrolytic",
    side: "Top",
    position: { x: 8, y: 56 },
    rotation: 0,
    height: 16,
    footprint: { width: 8, depth: 8 },
    supplier: "Nichicon",
    partNumber: "UPW1V221MPD",
    status: "Verified",
    tolerance: { xy: 0.2, rot: 3 },
    offsetMm: 0.069,
  },

  // --------------------------------------------------------- Connectors
  {
    id: "c-j1",
    refDes: "J1",
    name: "Ethernet Jack",
    package: "RJ45 Shielded",
    kind: "Connector",
    side: "Top",
    position: { x: 13, y: 20 },
    rotation: 0,
    height: 13.5,
    footprint: { width: 16, depth: 21 },
    supplier: "Amphenol",
    partNumber: "RJHSE-5380",
    status: "Verified",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.058,
  },
  {
    id: "c-j2",
    refDes: "J2",
    name: "USB Type-B Port",
    package: "USB-B Through-Hole",
    kind: "Connector",
    side: "Top",
    position: { x: 12, y: 44 },
    rotation: 0,
    height: 11,
    footprint: { width: 12, depth: 16 },
    supplier: "Molex",
    partNumber: "67068-8000",
    status: "Verified",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.076,
  },
  {
    id: "c-j3",
    refDes: "J3",
    name: "Terminal Block",
    package: "3.81mm 4-Position",
    kind: "Connector",
    side: "Top",
    position: { x: 92, y: 58 },
    rotation: 90,
    height: 10,
    footprint: { width: 16, depth: 8 },
    supplier: "Phoenix Contact",
    partNumber: "1803581",
    status: "Critical",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.134,
    notes: "Body encroaches on the keep-out around H8. Collision risk.",
    calloutIndex: 3,
  },
  {
    id: "c-j4",
    refDes: "J4",
    name: "Expansion Header",
    package: "2x8 2.54mm",
    kind: "Connector",
    side: "Top",
    position: { x: 64, y: 8 },
    rotation: 0,
    height: 8.5,
    footprint: { width: 20, depth: 5 },
    supplier: "Samtec",
    partNumber: "TSW-108-07-G-D",
    status: "Verified",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.041,
  },
  {
    id: "c-j5",
    refDes: "J5",
    name: "JTAG Header",
    package: "2x5 1.27mm",
    kind: "Connector",
    side: "Top",
    position: { x: 38, y: 8 },
    rotation: 0,
    height: 5.8,
    footprint: { width: 12, depth: 5 },
    supplier: "Samtec",
    partNumber: "FTSH-105-01-L-DV-K",
    status: "Verified",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.035,
  },
  {
    id: "c-j6",
    refDes: "J6",
    name: "DC Power Jack",
    package: "Barrel 2.1mm",
    kind: "Connector",
    side: "Top",
    position: { x: 92, y: 14 },
    rotation: 90,
    height: 11,
    footprint: { width: 14, depth: 9 },
    supplier: "CUI Devices",
    partNumber: "PJ-102AH",
    status: "Verified",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.062,
  },
  {
    id: "c-j7",
    refDes: "J7",
    name: "Fan Header",
    package: "2.54mm 3-Position",
    kind: "Connector",
    side: "Top",
    position: { x: 80, y: 8 },
    rotation: 0,
    height: 8.5,
    footprint: { width: 8, depth: 5 },
    supplier: "Molex",
    partNumber: "22-23-2031",
    status: "Verified",
    tolerance: { xy: 0.15, rot: 2 },
    offsetMm: 0.049,
  },

  // ----------------------------------------------------------- Passives
  {
    id: "c-r102",
    refDes: "R102",
    name: "Current Sense Resistor",
    package: "2512",
    kind: "Passive",
    side: "Top",
    position: { x: 56, y: 40 },
    rotation: 0,
    height: 0.6,
    footprint: { width: 6.4, depth: 3.2 },
    supplier: "Vishay",
    partNumber: "WSL2512R0100FEA",
    status: "Warning",
    tolerance: { xy: 0.1, rot: 1.5 },
    offsetMm: 0.152,
    notes: "X/Y offset exceeds the 0.100 mm limit. Flagged for review.",
  },
  {
    id: "c-c236",
    refDes: "C236",
    name: "Ceramic Capacitor",
    package: "1206",
    kind: "Passive",
    side: "Top",
    position: { x: 44, y: 50 },
    rotation: 0,
    height: 2.1,
    footprint: { width: 3.2, depth: 1.6 },
    supplier: "Murata",
    partNumber: "GRM31CR61E106KA12L",
    status: "Warning",
    tolerance: { xy: 0.08, rot: 1 },
    offsetMm: 0.044,
    notes: "Body height 2.10 mm exceeds the 2.00 mm profile limit.",
  },
  {
    id: "c-r1",
    refDes: "R1",
    name: "Pull-up Resistor",
    package: "0603",
    kind: "Passive",
    side: "Top",
    position: { x: 52, y: 36 },
    rotation: 90,
    height: 0.45,
    footprint: { width: 1.6, depth: 0.8 },
    supplier: "Yageo",
    partNumber: "RC0603FR-0710KL",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.021,
  },
  {
    id: "c-r2",
    refDes: "R2",
    name: "Pull-up Resistor",
    package: "0603",
    kind: "Passive",
    side: "Bottom",
    position: { x: 52, y: 28 },
    rotation: 90,
    height: 0.45,
    footprint: { width: 1.6, depth: 0.8 },
    supplier: "Yageo",
    partNumber: "RC0603FR-0710KL",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.026,
  },
  {
    id: "c-r3",
    refDes: "R3",
    name: "Series Termination",
    package: "0805",
    kind: "Passive",
    side: "Top",
    position: { x: 62, y: 34 },
    rotation: 0,
    height: 0.5,
    footprint: { width: 2, depth: 1.25 },
    supplier: "Vishay",
    partNumber: "CRCW080533R0FKEA",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.018,
  },
  {
    id: "c-r4",
    refDes: "R4",
    name: "Feedback Divider",
    package: "0603",
    kind: "Passive",
    side: "Top",
    position: { x: 34, y: 42 },
    rotation: 0,
    height: 0.45,
    footprint: { width: 1.6, depth: 0.8 },
    supplier: "Yageo",
    partNumber: "RC0603FR-0722KL",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.03,
  },
  {
    id: "c-r5",
    refDes: "R5",
    name: "Gate Resistor",
    package: "0805",
    kind: "Passive",
    side: "Top",
    position: { x: 28, y: 46 },
    rotation: 0,
    height: 0.5,
    footprint: { width: 2, depth: 1.25 },
    supplier: "Vishay",
    partNumber: "CRCW08054R70FKEA",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.024,
  },
  {
    id: "c-c6",
    refDes: "C6",
    name: "Decoupling Capacitor",
    package: "0402",
    kind: "Passive",
    side: "Top",
    position: { x: 42, y: 38 },
    rotation: 0,
    height: 0.3,
    footprint: { width: 1, depth: 0.5 },
    supplier: "Murata",
    partNumber: "GRM155R61A104KA01D",
    status: "Verified",
    tolerance: { xy: 0.05, rot: 1 },
    offsetMm: 0.015,
  },
  {
    id: "c-c7",
    refDes: "C7",
    name: "Decoupling Capacitor",
    package: "0402",
    kind: "Passive",
    side: "Bottom",
    position: { x: 42, y: 26 },
    rotation: 0,
    height: 0.3,
    footprint: { width: 1, depth: 0.5 },
    supplier: "Murata",
    partNumber: "GRM155R61A104KA01D",
    status: "Verified",
    tolerance: { xy: 0.05, rot: 1 },
    offsetMm: 0.017,
  },
  {
    id: "c-c8",
    refDes: "C8",
    name: "Bypass Capacitor",
    package: "0603",
    kind: "Passive",
    side: "Top",
    position: { x: 54, y: 46 },
    rotation: 0,
    height: 0.45,
    footprint: { width: 1.6, depth: 0.8 },
    supplier: "Samsung",
    partNumber: "CL10B104KB8NNNC",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.022,
  },
  {
    id: "c-c9",
    refDes: "C9",
    name: "Bypass Capacitor",
    package: "0603",
    kind: "Passive",
    side: "Top",
    position: { x: 70, y: 34 },
    rotation: 0,
    height: 0.45,
    footprint: { width: 1.6, depth: 0.8 },
    supplier: "Samsung",
    partNumber: "CL10B104KB8NNNC",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.029,
  },
  {
    id: "c-c10",
    refDes: "C10",
    name: "Timing Capacitor",
    package: "0402",
    kind: "Passive",
    side: "Bottom",
    position: { x: 36, y: 30 },
    rotation: 0,
    height: 0.3,
    footprint: { width: 1, depth: 0.5 },
    supplier: "Murata",
    partNumber: "GRM1555C1H220JA01D",
    status: "Verified",
    tolerance: { xy: 0.05, rot: 1 },
    offsetMm: 0.013,
  },
  {
    id: "c-l1",
    refDes: "L1",
    name: "Power Inductor",
    package: "1210",
    kind: "Passive",
    side: "Top",
    position: { x: 20, y: 50 },
    rotation: 0,
    height: 2.5,
    footprint: { width: 3.2, depth: 2.5 },
    supplier: "Murata",
    partNumber: "LQH32PN100MN0L",
    status: "Verified",
    tolerance: { xy: 0.08, rot: 1.5 },
    offsetMm: 0.039,
  },
  {
    id: "c-l2",
    refDes: "L2",
    name: "Ferrite Bead",
    package: "0805",
    kind: "Passive",
    side: "Bottom",
    position: { x: 16, y: 36 },
    rotation: 0,
    height: 0.9,
    footprint: { width: 2, depth: 1.25 },
    supplier: "TDK",
    partNumber: "MPZ2012S601AT000",
    status: "Verified",
    tolerance: { xy: 0.06, rot: 1 },
    offsetMm: 0.027,
  },
  {
    id: "c-d1",
    refDes: "D1",
    name: "Schottky Diode",
    package: "SOD-123",
    kind: "Passive",
    side: "Bottom",
    position: { x: 26, y: 40 },
    rotation: 0,
    height: 1.1,
    footprint: { width: 2.7, depth: 1.6 },
    supplier: "onsemi",
    partNumber: "MBR0540T1G",
    status: "Verified",
    tolerance: { xy: 0.08, rot: 1.5 },
    offsetMm: 0.034,
  },
  {
    id: "c-d2",
    refDes: "D2",
    name: "TVS Diode",
    package: "SMA",
    kind: "Passive",
    side: "Top",
    position: { x: 84, y: 20 },
    rotation: 0,
    height: 2.3,
    footprint: { width: 4.3, depth: 2.6 },
    supplier: "Littelfuse",
    partNumber: "SMAJ24CA",
    status: "Verified",
    tolerance: { xy: 0.08, rot: 1.5 },
    offsetMm: 0.046,
  },
  {
    id: "c-y1",
    refDes: "Y1",
    name: "Crystal Oscillator",
    package: "3225",
    kind: "Passive",
    side: "Top",
    position: { x: 60, y: 52 },
    rotation: 0,
    height: 0.8,
    footprint: { width: 3.2, depth: 2.5 },
    supplier: "Epson",
    partNumber: "FA-238 25.0000MB",
    status: "Verified",
    tolerance: { xy: 0.05, rot: 1 },
    offsetMm: 0.02,
  },

  // -------------------------------------------------------- Mechanical
  {
    id: "c-hs1",
    refDes: "HS1",
    name: "Extruded Heatsink",
    package: "Board-Level 26mm",
    kind: "Mechanical",
    side: "Top",
    position: { x: 52, y: 68 },
    rotation: 0,
    height: 18,
    footprint: { width: 26, depth: 16 },
    supplier: "Wakefield-Vette",
    partNumber: "658-40ABPE",
    status: "Verified",
    tolerance: { xy: 0.3, rot: 3 },
    offsetMm: 0.118,
  },
  {
    id: "c-mh1",
    refDes: "MH1",
    name: "Mounting Standoff",
    package: "M3 Hex 6mm",
    kind: "Mechanical",
    side: "Top",
    position: { x: 5, y: 5 },
    rotation: 0,
    height: 6,
    footprint: { width: 6, depth: 6 },
    supplier: "Würth Elektronik",
    partNumber: "970060321",
    status: "Verified",
    tolerance: { xy: 0.25, rot: 5 },
    offsetMm: 0.081,
  },
  {
    id: "c-mh2",
    refDes: "MH2",
    name: "Mounting Standoff",
    package: "M3 Hex 6mm",
    kind: "Mechanical",
    side: "Top",
    position: { x: 95, y: 5 },
    rotation: 0,
    height: 6,
    footprint: { width: 6, depth: 6 },
    supplier: "Würth Elektronik",
    partNumber: "970060321",
    status: "Verified",
    tolerance: { xy: 0.25, rot: 5 },
    offsetMm: 0.077,
  },
  {
    id: "c-mh3",
    refDes: "MH3",
    name: "Mounting Standoff",
    package: "M3 Hex 6mm",
    kind: "Mechanical",
    side: "Top",
    position: { x: 5, y: 75 },
    rotation: 0,
    height: 6,
    footprint: { width: 6, depth: 6 },
    supplier: "Würth Elektronik",
    partNumber: "970060321",
    status: "Verified",
    tolerance: { xy: 0.25, rot: 5 },
    offsetMm: 0.093,
  },
  {
    id: "c-mh4",
    refDes: "MH4",
    name: "Mounting Standoff",
    package: "M3 Hex 6mm",
    kind: "Mechanical",
    side: "Top",
    position: { x: 95, y: 75 },
    rotation: 0,
    height: 6,
    footprint: { width: 6, depth: 6 },
    supplier: "Würth Elektronik",
    partNumber: "970060321",
    status: "Verified",
    tolerance: { xy: 0.25, rot: 5 },
    offsetMm: 0.086,
  },
];
